jwt:
  secretKey:

s3:
  access-key:
  secret-key:
  bucket:

barcode:
    api:
        product:
            base-url: https://openapi.foodsafetykorea.go.kr/api
            service-key: 275556b048794838ae7e